site_name: Event-Driven Solutions in Hybrid Cloud - Jerome Boyer 
repo_url: https://github.com/jbcodeforce/eda-studies.git
site_url: https://jeromeboyer.net/eda-studies
copyright: Copyright &copy; 2018 - 2024 Jerome Boyer
nav:
  - Introduction: index.md                        # reviewed 03/2024
  - EDA concepts: 
    - Reference architecture: concepts/eda.md     # reviewed 03/2024
    - From SOA to EDA: concepts/soa-eda.md
    - Event backbone: concepts/backbone.md
    - Legacy integration: concepts/legacy-itg.md  # reviewed 07/2024
    - Data pipeline: concepts/data-pipeline.md
  - Methodology:
    - Event Storming: event-storming/index.md
    - Domain driven design: ddd/index.md
    - EDA Assessment : ddd/eda_assessment.md
    - Vaccine Examples: event-storming/vaccine-dt-es-ddd.md
  - Design patterns:
    - Common patterns: patterns/index.md
    - Messaging vs events: patterns/events-versus-messages/index.md
    - Devising the data models: patterns/model/index.md
    - Saga: patterns/saga/index.md
    - Event Sourcing: patterns/event-sourcing/index.md
    - CQRS: patterns/cqrs/index.md
    - Reactive: patterns/reactive/index.md
    - Flow architecture: patterns/flow-architectures.md
    - Dead letter queue: patterns/dlq/index.md
    - Data lineage: patterns/data-lineage/index.md
    - Governance: patterns/governance/index.md     # updated 07/2024 - still need work
  - Demonstrations:
    - GitOps - IaC: solutions/gitops_IaC/index.md
    - Real-time Inventory: https://jbcodeforce.github.io/eda-rt-inventory/
  - OOS technologies:
    - Kafka: techno/kafka/index.md     # reviewed 07/2024
    - Kafka FAQ: techno/kafka/faq.md   # reviewed 07/2024
    - Kafka Producer: techno/kafka/producer.md
    - Kafka Consumer: techno/kafka/consumer.md
    - Kafka Streams: techno/kstreams/index.md
    - Kafka Connect: techno/kafka-connect/index.md
    #- Mirror Maker 2: techno/mirrormaker/index.md
    - Flink: https://jbcodeforce.github.io/flink-studies
    - Active MQ: https://jbcodeforce.github.io/aws-messaging-study/activemq/
    - Rabbit MQ: https://jbcodeforce.github.io/aws-messaging-study/rabbitmq/
  - AWS technologies:
    - Duplicate with EB: solutions/autonomous-car/es-duplicate-evt.md
    - Streaming: https://jbcodeforce.github.io/yarfba/kinesis
    - MSK: https://jbcodeforce.github.io/yarfba/serverless/msk
    - AWS messaging: https://jbcodeforce.github.io/aws-messaging-study
    - AWS SQS: https://jbcodeforce.github.io/aws-messaging-study/sqs/
    - Autonomous Car Ride: https://jbcodeforce.github.io/autonomous-car-iac
    
  - IBM technologies: 
    - Assets: ibm-assets.md
    - MQ: techno/ibm-mq/index.md
theme: 
  name: material
  logo: images/logo.drawio.png
  favicon: images/logo-blue.drawio.png
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      # - navigation.tabs
      #- navigation.tabs.sticky
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      #- navigation.expand
      - navigation.top
      - navigation.footer


extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocs-video
  - mermaid2
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/jbcodeforce'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/jeromeboyer'
    - icon: fontawesome/solid/paper-plane
      mailto: jerome@intelligent-automations.com