site_name: Event-Driven Architecture Book - Jerome Boyer 
repo_url: https://github.com/jbcodeforce/eda-studies.git
site_url: https://jbcodeforce.github.io/eda-studies
nav:
  - Introduction: index.md
  - EDA concepts: 
    - Reference architecture: concepts/eda.md
    - From SOA to EDA: concepts/soa-eda.md
    - Event backbone: concepts/backbone.md
  - Methodology:
    - Event Storming: event-storming/index.md
    - Domain driven design: ddd/index.md
    - Vaccine Examples: event-storming/vaccine-dt-es-ddd.md
  - Design patterns:
    - Common patterns: patterns/index.md
    - Messaging vs events: patterns/events-versus-messages/index.md
    - Devising the data models: patterns/model/index.md
    - Saga: patterns/saga/index.md
    - Event Sourcing: patterns/event-sourcing/index.md
    - CQRS: patterns/cqrs/index.md
    - Reactive: patterns/reactive/index.md
    - Flow architecture: patterns/flow-architectures.md
    - Dead letter queue: patterns/dlq/index.md
    - Data lineage: patterns/data-lineage/index.md
    # - Governance: patterns/governance/index.md
  - OOS technologies:
    - Kafka: techno/kafka/index.md
    - Kafka Consumer: techno/kafka/consumer.md
    - Kafka Streams: techno/kstreams/index.md
    - Kafka Connect: techno/kafka-connect/index.md
    - Mirror Maker 2: techno/mirrormaker/index.md
  - AWS technologies:
      - Streaming: https://jbcodeforce.github.io/yarfba/kinesis
      - AWS messaging: https://jbcodeforce.github.io/aws-messaging-study
      - Autonomous Car Ride: https://jbcodeforce.github.io/autonomous-car-iac
      - Duplicate with ES: solutions/autonomous-car/es-duplicate-evt.md
  - IBM technologies: 
      - Assets: ibm-assets.md
      - MQ: techno/ibm-mq/index.md
theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      #- navigation.expand
      - navigation.top

  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocs-video
  - mermaid2
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true