site_name: Event-Driven Architecture Studies
repo_url: https://github.com/jbcodeforce/eda-studies.git
nav:
  - Introduction: index.md
  - EDA concepts: eda.md
  - Methodology:
    - Event Storming: event-storming/index.md
    - Domain driven design: ddd/index.md
    - Vaccine Examples: event-storming/vaccine-dt-es-ddd.md
  - Design patterns:
    - Common patterns: patterns/index.md
    - Messaging vs events: patterns/events-versus-messages/index.md
    - Devising the data models: patterns/model/index.md
    - Saga: patterns/saga/index.md
    - Event Sourcing: patterns/event-sourcing/index.md
    - CQRS: patterns/cqrs/index.md
    - Reactive: patterns/reactive/index.md
    - Flow architecture: patterns/flow-architectures.md
    - Dead letter queue: patterns/dlq/index.md
  - OOS technologies:
    - Kafka: techno/kafka/index.md
    - Kafka Consumer: techno/kafka/consumer.md
    - Kafka Connect: techno/kafka-connect/index.md
    - Mirror Maker 2: techno/mirrormaker/index.md
  - AWS technologies:
      - Streaming: https://jbcodeforce.github.io/aws-studies/kinesis
      - EventBridge: aws/eventbridge.md
      - AWS messaging: https://jbcodeforce.github.io/aws-messaging-study
  - AWS assets: 
      - Autonomous Car Ride: solutions/autonomous-car/index.md
      - Duplicate with ES: solutions/autonomous-car/es-duplicate-evt.md
  - IBM technologies: 
      - Assets: ibm-assets.md
      - MQ: techno/ibm-mq/index.md
  - AWS studies: https://jbcodeforce.github.io/aws-studies
  - Return to main: https://jbcodeforce.github.io
theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      - navigation.tracking
      # - navigation.sections
      # - navigation.expand
      - navigation.tabs.sticky
      # - navigation.top

  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocs-video
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true