site_name: Event-Driven Architecture Studies
repo_url: https://github.com/jbcodeforce/eda-studies.git
nav:
  - Introduction: index.md
  - EDA concepts: eda.md
  - Methodology:
    - Event Storming: event-storming/index.md
    - Domain driven design: ddd/index.md
  - Design patterns:
    - Common patterns: patterns/index.md
    - CQRS: patterns/cqrs/index.md
  - AWS technologies:
      - Streaming: https://jbcodeforce.github.io/aws-studies/kinesis
      - EventBridge: aws/eventbridge.md
  - AWS assets: 
      - Autonomous Car Ride: solutions/autonomous-car/index.md
  - IBM assets: ibm-assets.md
  - Return to main: https://jbcodeforce.github.io
theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      - navigation.tracking
      # - navigation.sections
      # - navigation.expand
      - navigation.tabs.sticky
      # - navigation.top

  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true